### ISSUE TITLE
Page is very ugly

### ISSUE THREAD

**Issue by joachimdewaelheyns** [d-mg/time#5]

**Comment by d-mg** [comment]
Why don't you make a suggestion @joachimdewaelheyns ?

**Comment by joachimdewaelheyns** [comment]
![more-attractive](https://cloud.githubusercontent.com/assets/4677499/17933486/91f734e0-6a14-11e6-9f11-c60cb65f689d.PNG)

**Comment by d-mg** [comment]
Let's wait for actually making it pretty when we are done with: Build a menu bar that hides the input fields #3
After I suggest to make themes that can be chosen. Starting with one but implementing it with thought of having a choice.

**Comment by d-mg** [comment]
Milestone to start this ticket has been accomplished, ready for implementation.

**Comment by d-mg** [comment]
Made changes to be less ugly
